# Generated by Django 2.0.2 on 2018-03-15 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habitapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date of activity')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitapi.Habit')),
            ],
        ),
    ]
