# Generated by Django 2.0.2 on 2018-03-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitapi', '0002_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='habit',
            name='progress',
        ),
        migrations.AddField(
            model_name='tag',
            name='habit',
            field=models.ManyToManyField(blank=True, null=True, to='habitapi.Habit'),
        ),
    ]
