# Generated by Django 2.0.2 on 2018-03-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitapi', '0003_auto_20180317_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='habit',
            field=models.ManyToManyField(blank=True, to='habitapi.Habit'),
        ),
    ]
